### ISSUE TITLE
Umbrella: Update Wycheproof test vectors to v1

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-crypto#165]
This issue is an umbrella issue where we can keep track of my efforts upgrading all Wycheproof test vectors from [v0](https://github.com/google/wycheproof/tree/master/testvectors) to [v1](https://github.com/google/wycheproof/tree/master/testvectors_v1).

- [x] `aes_gcm` - #156  
- [x] `chacha20_polt1305` - #157
- [x] `ecdh_secp256r1_test` - #160
- [x] `ecdh_secp256r1_ecpoint_test` - #158 
- [x] `ecdh_secp384r1_test` - #162
- [x] `ecdh_secp384r1_ecpoint_test` - #161
- [x] `ecdh_secp521r1_test` - #163
- [x] `ecdh_secp521r1_ecpoint_test` - #164 
- [x] `ecdsa_secp256r1_sha256_test` open PR #166
- [x] `ecdsa_secp256r1_sha512_test` open PR #166
- [x] `ecdsa_secp384r1_sha384_test` open PR #166
- [x] `ecdsa_secp384r1_sha512_test` open PR #166
- [x] `ecdsa_secp521r1_sha512_test` open PR #166
- [x] `eddsa_test` (renamed -> `ed25519_test`) - #159 
- [x] `x25519_test` - #155

**Comment by Lukasa** [comment]
Hey @Sajjon, are there any further vectors you'd like to add as part of this ticket?

**Comment by Sajjon** [comment]
@Lukasa I think I'm done for now, I will close this issue.
